server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/users/**
          - id: post-service
            uri: lb://post-service
            predicates:
              - Path=/post/**
          - id: feed-service
            uri: lb://feed-service
            predicates:
              - Path=/feed/**
          - id: analytics-service
            uri: lb://analytics-service
            predicates:
              - Path=/analytics/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: gateway-service
