server:
  port: 8081

jwt:
  secret: this_is_a_very_secure_and_long_secret_key_64_chars_minimum_which_is_supposed_to_be
  expiration: 3600000

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/users/**
          - id: post-service
            uri: lb://post-service
            predicates:
              - Path=/post/**
          - id: feed-service
            uri: lb://feed-service
            predicates:
              - Path=/feed/**
          - id: analytics-service
            uri: lb://analytics-service
            predicates:
              - Path=/analytics/**
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: gateway-service
